### ISSUE TITLE
承認待ちフォームの画面がアンケートママになってる(^^;

### ISSUE THREAD

**Issue by RyujiAMANO** [NetCommons3/Registrations#30]
アンケートとちがってフォーム作成後も再編集できるし、登録されたデータ削除もあるから、テストモードなくても良さそう。

**Comment by RyujiAMANO** [comment]
テスト投稿の一覧とかもないし、テストモードなしでいいかなぁ。

**Comment by RikaFujiwara** [comment]
登録フォームはなくてよいと思いますよー
アンケート、小テストは発行したら変えられなくなっちゃうから、苦肉の策でのテストモードです。

**Comment by RyujiAMANO** [comment]
公開中と一時保存があることを考えるとテストモードでの回答はやはりいりそう。
ってことで残すけど説明は簡易版だけでよさそう
